### ISSUE TITLE
Support for Cargo Install

### ISSUE THREAD

**Issue by DeusFerrariis** [giacomo-b/shiba#1]
As mentioned in title. Support for cargo install would be appreciated.

**Comment by giacomo-b** [comment]
Thanks for the suggestion, I will get to that asap

**Comment by giacomo-b** [comment]
I didn't want to add shiba to [crates.io](https://crates.io/), but it can be installed directly from GitHub with

```console
cargo install --git https://github.com/giacomo-b/shiba.git
```
